# -*- coding: utf-8 -*-
"""01_data_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ban0FX8MELXoBClnVlpXL0LakajwZW0
"""

from datasets import load_dataset, DatasetDict
import random

sft_raw = load_dataset("HuggingFaceTB/smoltalk", "all", split="train")
print(f"SmolTalk full size: {len(sft_raw):,} samples")
print(f"Features: {list(sft_raw.features.keys())}")
print(f"\nSample (first message):\n{sft_raw[0]['messages'][0]}")

def filter_sft_quality(example):
    """
    Remove low-quality samples that would hurt training.
    Criteria:
    1. Must have at least 2 messages (user + assistant)
    2. Assistant response must be >50 chars (not trivially short)
    3. Assistant response must be <2000 chars (avoid repetitive/bloated)
    4. No broken/empty messages
    """
    messages = example.get('messages', [])
    if len(messages) < 2:
        return False

    assistant_msgs = [m for m in messages if m['role'] == 'assistant']
    if not assistant_msgs:
        return False

    last_response = assistant_msgs[-1]['content']
    if not last_response or not isinstance(last_response, str):
        return False

    response_len = len(last_response.strip())
    return 50 < response_len < 2000

sft_filtered = sft_raw.filter(
    filter_sft_quality,
    num_proc=2,
    desc="Filtering SFT quality"
)
print(f"After quality filter: {len(sft_filtered):,} samples (from {len(sft_raw):,})")

random.seed(42)
N_SFT = 15_000
sft_dataset = sft_filtered.select(random.sample(range(len(sft_filtered)), min(N_SFT, len(sft_filtered))))
print(f"Final SFT dataset: {len(sft_dataset):,} samples")

import os

BASE_DIR = "/content"
os.makedirs(f"{BASE_DIR}/datasets", exist_ok=True)

sft_dataset.save_to_disk(f"{BASE_DIR}/datasets/sft_smoltalk_15k")
print(f"✅ SFT dataset saved: {BASE_DIR}/datasets/sft_smoltalk_15k")

simpo_raw = load_dataset("trl-lib/ultrafeedback_binarized", split="train")
print(f"UltraFeedback full size: {len(simpo_raw):,} pairs")

def filter_simpo_quality(example):
    """
    Filter preference pairs for quality:
    1. Score margin must be ≥ 1.0 (clear preference signal)
    2. Both responses must be non-empty
    3. Chosen must be longer than rejected by ≤ 3× (avoid length bias)
    """
    score_chosen = example.get('score_chosen', 0)
    score_rejected = example.get('score_rejected', 0)

    if (score_chosen - score_rejected) < 1.0:
        return False

    chosen_msgs = example.get('chosen', [])
    rejected_msgs = example.get('rejected', [])

    if not chosen_msgs or not rejected_msgs:
        return False

    def last_assistant(msgs):
        for m in reversed(msgs):
            if m.get('role') == 'assistant':
                return m.get('content', '')
        return ''

    chosen_text = last_assistant(chosen_msgs)
    rejected_text = last_assistant(rejected_msgs)

    if not chosen_text or not rejected_text:
        return False

    ratio = len(chosen_text) / max(len(rejected_text), 1)
    if ratio > 3.0 or ratio < 0.33:
        return False

    return True

simpo_filtered = simpo_raw.filter(filter_simpo_quality, num_proc=2, desc="Filtering SimPO quality")
print(f"After quality filter: {len(simpo_filtered):,} pairs")

N_SIMPO = 15_000
simpo_dataset = simpo_filtered.select(range(min(N_SIMPO, len(simpo_filtered))))
simpo_dataset.save_to_disk(f"{BASE_DIR}/datasets/simpo_ultrafeedback_15k")
print(f"✅ SimPO dataset saved")

gsm8k = load_dataset("openai/gsm8k", "main", split="train")
print(f"GSM8K train: {len(gsm8k):,} problems")
print(f"Sample: {gsm8k[0]}")

def format_gsm8k_for_grpo(example):
    """Format GSM8K for GRPO: extract numeric answer for reward function."""
    import re
    answer_text = example['answer']
    match = re.search(r'####\s*([\d,\-]+)', answer_text)
    numeric_answer = match.group(1).replace(',', '') if match else None

    return {
        'prompt': [
            {'role': 'system', 'content': 'You are a precise math problem solver. Think step by step, then give your final answer as a number after "#### ".'},
            {'role': 'user', 'content': example['question']}
        ],
        'answer': numeric_answer,
        'full_solution': answer_text,
    }

grpo_dataset = gsm8k.map(format_gsm8k_for_grpo, desc="Formatting GSM8K")
grpo_dataset = grpo_dataset.filter(lambda x: x['answer'] is not None)
grpo_dataset.save_to_disk(f"{BASE_DIR}/datasets/grpo_gsm8k")
print(f"✅ GRPO dataset ready: {len(grpo_dataset):,} problems (all with numeric answers)")

import matplotlib.pyplot as plt
import numpy as np
import os

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
fig.suptitle("Dataset Analysis — Post-Training 2026", fontsize=14, fontweight='bold')

sft_lengths = []
for ex in sft_dataset.select(range(500)):
    asst = [m for m in ex['messages'] if m['role'] == 'assistant']
    if asst:
        sft_lengths.append(len(asst[-1]['content']))

axes[0].hist(sft_lengths, bins=40, color='#2196F3', alpha=0.8, edgecolor='white')
axes[0].axvline(np.mean(sft_lengths), color='red', linestyle='--', label=f'Mean: {np.mean(sft_lengths):.0f}')
axes[0].set_title("SFT Response Lengths (chars)")
axes[0].set_xlabel("Characters")
axes[0].legend()

margins = [ex['score_chosen'] - ex['score_rejected'] for ex in simpo_dataset.select(range(500))]
axes[1].hist(margins, bins=30, color='#4CAF50', alpha=0.8, edgecolor='white')
axes[1].axvline(np.mean(margins), color='red', linestyle='--', label=f'Mean margin: {np.mean(margins):.2f}')
axes[1].set_title("SimPO Preference Score Margins")
axes[1].set_xlabel("Score Difference (chosen - rejected)")
axes[1].legend()

gsm_lengths = [len(ex['question']) for ex in grpo_dataset.select(range(500))]
axes[2].hist(gsm_lengths, bins=30, color='#FF9800', alpha=0.8, edgecolor='white')
axes[2].axvline(np.mean(gsm_lengths), color='red', linestyle='--', label=f'Mean: {np.mean(gsm_lengths):.0f}')
axes[2].set_title("GRPO Question Lengths (chars)")
axes[2].set_xlabel("Characters")
axes[2].legend()

plt.tight_layout()
os.makedirs(f"{BASE_DIR}/logs", exist_ok=True)
plt.savefig(f"{BASE_DIR}/logs/dataset_analysis.png", dpi=150, bbox_inches='tight')
plt.show()
print(f"✅ EDA plot saved")