# -*- coding: utf-8 -*-
"""02_sft_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12TVVUvSayXQBJxzQqPo_46tN3zCQf6ls
"""

!pip install unsloth
from unsloth import FastLanguageModel
import torch

MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"
MAX_SEQ_LEN = 2048
LORA_RANK = 64

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_ID,
    max_seq_length=MAX_SEQ_LEN,
    dtype=None,
    load_in_4bit=True,
)

print(f"✅ Base model loaded")
print(f"   Parameters: {sum(p.numel() for p in model.parameters()) / 1e6:.1f}M")
print(f"   Dtype: {next(model.parameters()).dtype}")

model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_RANK,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha=LORA_RANK * 2,
    lora_dropout=0.05,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
    use_rslora=True,
    loftq_config=None,
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\n✅ LoRA adapters attached")
print(f"   Total params:     {total_params / 1e6:.2f}M")
print(f"   Trainable params: {trainable_params / 1e6:.2f}M ({100 * trainable_params / total_params:.2f}%)")

from datasets import load_dataset
from trl import SFTTrainer, SFTConfig
from unsloth.chat_templates import get_chat_template

tokenizer = get_chat_template(tokenizer, chat_template="qwen-2.5")

sft_dataset = load_dataset("HuggingFaceTB/smoltalk", "smol-rewrite", split="train[:15000]")

def apply_chat_template(examples):
    """
    Convert messages list → formatted string with special tokens.
    """
    texts = []
    for msgs in examples['messages']:
        text = tokenizer.apply_chat_template(
            msgs,
            tokenize=False,
            add_generation_prompt=False,
        )
        texts.append(text)
    return {'text': texts}

sft_formatted = sft_dataset.map(
    apply_chat_template,
    batched=True,
    batch_size=1000,
    remove_columns=sft_dataset.column_names,
    desc="Applying chat template",
)

print(f"\n✅ Chat template applied")
print(f"Sample:\n{sft_formatted[0]['text'][:400]}")

import os
import wandb

BASE_DIR = "/content/drive/MyDrive/unsloth_checkpoints"

drive_out = f"{BASE_DIR}/checkpoints/sft"
os.makedirs(drive_out, exist_ok=True)
with open(f"{drive_out}/.write_test", "w") as f: f.write("ok")
os.remove(f"{drive_out}/.write_test")
print("✅ Drive writable — safe to start training")

wandb.init(
    project="rlhf-simpo-grpo-2026",
    name="01_sft_qwen25-1.5b_smoltalk15k",
    config={
        "model": MODEL_ID,
        "stage": "SFT",
        "dataset": "smoltalk_15k",
        "lora_rank": LORA_RANK,
        "max_seq_len": MAX_SEQ_LEN,
    }
)

sft_config = SFTConfig(

    output_dir=drive_out,
    num_train_epochs=2,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,


    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    weight_decay=0.01,


    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    optim="adamw_8bit",
    max_grad_norm=1.0,
    gradient_checkpointing=True,


    max_seq_length=MAX_SEQ_LEN,
    dataset_text_field="text",
    packing=True,
    dataset_num_proc=2,


    logging_steps=10,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=3,
    report_to="wandb",


    eval_strategy="no",
    seed=42,
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    args=sft_config,
    train_dataset=sft_formatted,
)

print("✅ Trainer ready")
print(f"   Output dir : {drive_out}")
print(f"   Checkpoints: every 100 steps → Drive")
print(f"   Steps total: ~306 | Epochs: 2 | EBS: 16")

import time, os

print("🚀 Starting SFT training...")
print(f"   Steps: {trainer.args.max_steps if trainer.args.max_steps > 0 else 'auto'}")
print(f"   Effective batch size: {sft_config.per_device_train_batch_size * sft_config.gradient_accumulation_steps}")
print(f"   Estimated time: ~45 min on T4")

start = time.time()
train_result = trainer.train()
elapsed = time.time() - start

print(f"\n✅ SFT Training complete in {elapsed/60:.1f} minutes")
print(f"   Final loss: {train_result.training_loss:.4f}")

final_out = f"{BASE_DIR}/checkpoints/sft/final_adapter"
os.makedirs(final_out, exist_ok=True)

model.save_pretrained(final_out)
tokenizer.save_pretrained(final_out)

required = {"adapter_config.json", "adapter_model.safetensors"}
saved = set(os.listdir(final_out))
missing = required - saved
if missing:
    raise RuntimeError(f"❌ Save incomplete — missing files: {missing}\nSaved: {saved}")

print(f"✅ SFT adapter verified on Drive: {saved}")

ckpt_dir = f"{BASE_DIR}/checkpoints/sft"
checkpoints = [d for d in os.listdir(ckpt_dir) if d.startswith("checkpoint-")]
print(f"✅ Checkpoints on Drive: {sorted(checkpoints)}")

wandb.finish()