# -*- coding: utf-8 -*-
"""3_GRPO_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yIk1QdF6XPmGyzoM2zQvBSDqfOgnBhW
"""

import subprocess

def _pip(cmd):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr[-400:])

_pip("pip uninstall -y trl bitsandbytes peft accelerate transformers 2>/dev/null")
_pip("pip install --quiet 'unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git'")
_pip("pip install --quiet trl peft bitsandbytes accelerate transformers datasets xformers einops wandb sentencepiece evaluate huggingface_hub")

import importlib
for lib in ["unsloth", "transformers", "trl", "peft", "bitsandbytes"]:
    try:
        mod = importlib.import_module(lib)
        print(f"OK {lib}: {getattr(mod, '__version__', 'loaded')}")
    except Exception as e:
        print(f"FAIL {lib}: {e}")
print("\n[OK] Now Runtime → Restart runtime, then run cells below.")

import os, re, gc, time, math
from decimal import Decimal, InvalidOperation
from typing import List

import torch
import wandb
from datasets import load_dataset
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template
from trl import GRPOTrainer, GRPOConfig

BASE_DIR = "/content/PostTraining_2026"
CKPT_DIR = f"{BASE_DIR}/checkpoints/grpo"
os.makedirs(CKPT_DIR, exist_ok=True)

CONFIG = {
    "model_id":      "Qwen/Qwen2.5-1.5B-Instruct",
    "simpo_hub":     "hemanthrajelangovan/Qwen2.5-1.5B-SimPO-2026",
    "grpo_hub":      "hemanthrajelangovan/Qwen2.5-1.5B-GRPO-2026",
    "max_seq_len":   2048,
    "seed":          42,
}

def vram(tag=""):
    a = torch.cuda.memory_allocated(0)/1e9
    r = torch.cuda.memory_reserved(0)/1e9
    print(f"VRAM [{tag}]: {a:.2f}G / {r:.2f}G")

vram("before")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=CONFIG["simpo_hub"],
    max_seq_length=CONFIG["max_seq_len"],
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_training(model)
model.train()
model.config.use_cache = False

tokenizer = get_chat_template(tokenizer, chat_template="qwen-2.5")
tokenizer.padding_side = "left"

print(f"[OK] Loaded SimPO: {CONFIG['simpo_hub']}")
vram("after")

raw = load_dataset("openai/gsm8k", "main", split="train")

SYSTEM_PROMPT = """You are a precise math problem solver. Solve step by step.
Show your reasoning clearly, then give the final numeric answer after '#### '.
Example:
Question: What is 2 + 3 * 4?
Step 1: 3 * 4 = 12
Step 2: 2 + 12 = 14
#### 14""".strip()

def fmt(x):
    m = re.search(r"####\s*([\-\d,\.]+)", x["answer"])
    num = m.group(1).replace(",", "") if m else None
    return {
        "prompt": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": x["question"]},
        ],
        "answer": num,
    }

train_data = raw.map(fmt).filter(lambda x: x["answer"] is not None)
print(f"Train: {len(train_data):,}")

def _to_str(x):
    if isinstance(x, str):
        return x
    if isinstance(x, list):
        try:
            return tokenizer.decode(x, skip_special_tokens=True)
        except:
            return " ".join(str(s) for s in x)
    return str(x)

def extract_numeric_answer(text: str):
    text = _to_str(text)
    if not text:
        return None
    m = re.search(r"####\s*([\-\d,\.]+)", text)
    if m:
        return m.group(1).replace(",", "").strip()
    m = re.search(r"(?:answer\s+is|answer\s*:)\s*([\-\d,\.]+)", text, re.IGNORECASE)
    if m:
        return m.group(1).replace(",", "").strip()
    clean = text.replace(",", "")
    nums = re.findall(r"[\-]?\d+(?:\.\d+)?", clean)
    valid = [n for n in nums if _safe_float(n)]
    return valid[-1] if valid else None

def _safe_float(x):
    try: float(x); return True
    except: return False

def _nums_equal(p, t):
    try: return Decimal(p) == Decimal(t)
    except:
        try: return abs(float(p) - float(t)) < 1e-6
        except: return False

def has_reasoning_steps(text: str) -> bool:
    """Detect presence of step-by-step reasoning."""
    text = _to_str(text)
    patterns = [
        r"step\s*\d+", r"first", r"second", r"then", r"therefore",
        r"calculate", r"=\s*[\d]+", r"let\s+(me|us)", r"since", r"because",
    ]
    return sum(1 for p in patterns if re.search(p, text, re.IGNORECASE)) >= 2

def reward_correctness(prompts, completions, answer, **kwargs):
    """
    1.0 = correct answer
    0.5 = wrong answer but has valid reasoning structure
    0.0 = no answer or gibberish
    """
    rewards = []
    for c, a in zip(completions, answer):
        c_str = _to_str(c)
        if not c_str or a is None:
            rewards.append(0.0); continue
        p = extract_numeric_answer(c_str)
        if p and _nums_equal(p, str(a)):
            rewards.append(1.0)
        elif has_reasoning_steps(c_str):
            rewards.append(0.5)
        else:
            rewards.append(0.0)
    return rewards

def reward_format_quality(prompts, completions, **kwargs):
    """0.0-0.3: step-by-step format, numbers, final answer marker."""
    rewards = []
    for c in completions:
        c_str = _to_str(c)
        if not c_str:
            rewards.append(0.0); continue
        s = 0.0
        if len(re.findall(r"\d+", c_str)) >= 3: s += 0.1
        wc = len(c_str.split())
        if 30 <= wc <= 300: s += 0.1
        if re.search(r"(####|final answer|the answer is)", c_str, re.IGNORECASE): s += 0.1
        rewards.append(round(s, 4))
    return rewards

def reward_no_repetition(prompts, completions, **kwargs):
    """-0.5 to 0: penalize repetition via bigram diversity."""
    rewards = []
    for c in completions:
        c_str = _to_str(c)
        if not c_str or len(c_str.split()) < 2:
            rewards.append(0.0); continue
        w = c_str.lower().split()
        b = [f"{w[i]}_{w[i+1]}" for i in range(len(w)-1)]
        r = 1.0 - len(set(b))/len(b)
        rewards.append(round(-0.5 * min(r*2, 1.0), 4))
    return rewards

def reward_verbosity_penalty(prompts, completions, **kwargs):
    """Penalty for too-short (<20 words) or too-long (>500 words) completions."""
    rewards = []
    for c in completions:
        c_str = _to_str(c)
        if not c_str:
            rewards.append(-0.3); continue
        wc = len(c_str.split())
        if wc < 20:
            rewards.append(-0.2)
        elif wc > 500:
            rewards.append(-0.1)
        else:
            rewards.append(0.0)
    return rewards

wandb.init(
    project="rlhf-simpo-grpo-2026",
    name="grpo_qwen25-1.5b_gsm8k_optimized",
    config={
        "model": CONFIG["model_id"],
        "stage": "GRPO",
        "dataset": "gsm8k",
        "num_generations": 8,
        "temperature": 0.9,
        "beta": 0.001,
        "learning_rate": 1e-5,
        "scheduler": "cosine_with_restarts",
        "epochs": 1,
        "max_steps": 300,
    },
)

grpo_config = GRPOConfig(
    num_generations=8,
    temperature=0.9,
    max_completion_length=1024,
    beta=0.001,
    use_vllm=False,
    output_dir=CKPT_DIR,
    num_train_epochs=1,
    max_steps=300,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=1e-5,
    lr_scheduler_type="cosine_with_restarts",
    lr_scheduler_kwargs={"num_cycles": 2},
    per_device_eval_batch_size=8,
    warmup_ratio=0.1,
    weight_decay=0.0,
    max_grad_norm=0.5,
    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported(),
    optim="adamw_8bit",
    gradient_checkpointing=True,
    logging_steps=5,
    save_strategy="steps",
    save_steps=50,
    save_total_limit=2,
    report_to="wandb",
    eval_strategy="no",
    seed=CONFIG["seed"],
)

trainer = GRPOTrainer(
    model=model,
    tokenizer=tokenizer,
    args=grpo_config,
    train_dataset=train_data,
    reward_funcs=[
        reward_correctness,
        reward_format_quality,
        reward_no_repetition,
        reward_verbosity_penalty,
    ],
    reward_weights=[2.0, 0.3, 1.0, 0.5],
)

print(f"Effective rollouts/step: {grpo_config.num_generations * grpo_config.gradient_accumulation_steps}")
print(f"Total optimization steps: 300 (set via max_steps)")

resume = os.path.exists(CKPT_DIR) and any(
    d.startswith("checkpoint-") for d in os.listdir(CKPT_DIR)
    if os.path.isdir(os.path.join(CKPT_DIR, d))
)
print(f"Starting GRPO (resume={resume})...")
print("Watch W&B for reward/mean increasing -- the 'aha' moment!")
vram("before")

try:
    t0 = time.time()
    r = trainer.train(resume_from_checkpoint=resume)
    elapsed = time.time() - t0
    print(f"Done in {elapsed/60:.1f} min | loss: {r.training_loss:.4f}")
finally:
    wandb.finish()

trainer.save_model(f"{CKPT_DIR}/final_adapter")
tokenizer.save_pretrained(f"{CKPT_DIR}/final_adapter")
print(f"[OK] GRPO adapter saved: {CKPT_DIR}/final_adapter")

import huggingface_hub

hf_token = os.environ.get("HF_TOKEN", "")
if not hf_token:
    print("HF_TOKEN not found in env.")
    try:
        hf_token = input("Paste your HuggingFace write token (or press Enter to skip): ").strip()
    except EOFError:
        hf_token = ""
    if not hf_token:
        hf_token = os.environ.get("HF_TOKEN", "")

hf_username = os.environ.get("HF_USERNAME", "")
if not hf_username:
    try:
        hf_username = os.environ.get("HF_USERNAME", "") or \
            input("Enter your HF username (or press Enter to skip): ").strip()
    except EOFError:
        hf_username = ""

if hf_token and hf_username:
    from huggingface_hub import login
    login(token=hf_token)
    repo_id = f"{hf_username}/Qwen2.5-1.5B-GRPO-2026"
    print(f"Pushing to {repo_id} ...")
    try:
        model.push_to_hub(repo_id, commit_message="GRPO adapter", token=hf_token)
        tokenizer.push_to_hub(repo_id, token=hf_token)
        print(f"[OK] Pushed to https://huggingface.co/{repo_id}")
    except Exception as e:
        print(f"[WARN] Push failed: {e}")
else:
    print("[NOTE] Adapter saved locally only — set HF_TOKEN & HF_USERNAME to push")

del model, tokenizer, trainer; gc.collect(); torch.cuda.empty_cache()
print("\n[DONE] GRPO complete.")





